version: '2'
services:
  base:
    image: node:12
    volumes:
      - nodemodules:/app/www/node_modules
    #   - next:/app/www/.next
      - .:/app/www/
    working_dir: /app/www/
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
volumes:
    nodemodules:
        external: true
    # next:
        # external: true